#! /bin/bash

NPER=`echo $SLURM_TASKS_PER_NODE | sed 's/(.*//'`
I=1900
nodes=`scontrol show hostname $SLURM_JOB_NODELIST` 2> /dev/null
for i in $nodes ; do
  ib=`ssh $i /sbin/ifconfig ib0 2>/dev/null | grep inet | sed "s/[ ][ ]*inet[ ][ ]*//" | sed "s/[ ].*//" | sed "s/addr://"` 2>/dev/null
  for j in `seq $NPER`; do
    echo $ib $I
    (( I = $I + 1 ))
  done
done
