DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT=$DIR/../..

module load intel/15.0.3 cxx11
cmake .. -DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_BUILD_TYPE=Release \
  -DOSPRAY_APPS_MODELVIEWER=OFF \
  -DOSPRAY_MODULE_LOADERS=OFF \
  -DOSPRAY_MODULE_OPENGL_UTIL=OFF \
  -DOSPRAY_APPS_QTVIEWER=OFF \
  -DOSPRAY_APPS_VOLUMEVIEWER=OFF \
  -DCMAKE_CXX_COMPILER=icpc \
  -DISPC_EXECUTABLE=`which ispc` \
  -DCMAKE_INSTALL_PREFIX=$PROJECT/install

	
